#!/usr/bin/env python3
###############################################################################
# Description: Library maintenance tool for Blade Runner Insight
# Author:      Tor Inge Skaar
# License:     MIT
###############################################################################

# Core modules
import os

# Third party modules
from docopt import docopt
import html5lib

usage = """
Usage:
    library list
    library prep ARTICLES...
    library -h | --help

Options:
    -h --help   Show this help description

"""


# Transform article(s) from markdown to html and apply to template
def prep(articlelist, library):
    for article in articlelist:
        md = library + '/' + article + '/article.md'
        print(md)
        if os.path.isfile(md):
            print("file exists")
        else:
            print('Unable to find {}'.format(md))


def main():
    # Argument parser
    args = docopt(usage)

    # We need to know the path of the library of articles
    library = os.environ.get('BRILIB')
    if library is None:
        print("Environment variable 'BRILIB' is not set. Please set it to the "
              "current path of the directory containing all articles")
        exit(2)

    # List all articles
    if args['list']:
        print('\n'.join(os.listdir(library)))
        exit()

    # Prep article
    if args['prep']:
        if args['ARTICLES'][0] == 'all':
            prep(os.listdir(library), library)
        else:
            prep(args['ARTICLES'], library)

if __name__ == "__main__":
    main()
